Repository uptagprojects/cartelera-cms, pull requests merged in 2024-10, with the labels that each got.

#8 user authenticator
  package-lock.json
  package.json
  src/api/cma/auth/authLocal.controller.ts
  src/api/cma/auth/routeAuth.ts
  src/api/cma/routeCMA.ts
  src/contexts/cma/users/application/authenticate/UserAuthenticator.ts
  src/contexts/cma/users/domain/PasswordDoesNotMeetLengthRequirements.ts
  src/contexts/cma/users/domain/User.ts
  src/contexts/cma/users/domain/UserEmail.ts
  src/contexts/cma/users/domain/UserEmailIsNotValid.ts
  src/contexts/cma/users/domain/UserId.ts
  src/contexts/cma/users/domain/UserName.ts
  src/contexts/cma/users/domain/UserNameLengthExceeded.ts
  src/contexts/cma/users/domain/UserPassword.ts
  src/contexts/cma/users/domain/UserRepository.ts
  src/contexts/cma/users/infrastructure/PostgresUserRepository.ts
  src/contexts/shared/domain/InvalidArgumentError.ts
  src/contexts/shared/infrastructure/PostgresPoolConnection.ts
Labels: enhancement

#11 feat: update micromatch to version 4.0.8
  package-lock.json
Labels: dependencies

#16 Using Octagon UI
  package-lock.json
  package.json
  src/app/fonts.ts
  src/app/globals.css
  src/app/guides/[id]/edit/page.tsx
  src/app/guides/[id]/page.tsx
  src/app/layout.tsx
  src/app/news/page.tsx
  src/app/page.tsx
  src/components/avatar/Avatar.tsx
  src/components/brand/Brand.tsx
  src/components/button/Button.tsx
  src/components/button/button.module.css
  src/components/nav/Nav.tsx
Labels: enhancement, dependencies

#27 Criteria and domain events fix
  .vscode/settings.json
  package-lock.json
  package.json
  src/api/cma/auth/authLocal.controller.ts
  src/api/cma/users/createUser.controller.ts
  src/app/api/[[...route]]/route.ts
  src/app/api/manage/users/[id]/route.ts
  src/app/api/manage/users/route.ts
  src/contexts/cda/announcements/application/search_by_criteria/AnnouncementsByCriteriaSearcher.ts
  src/contexts/cda/announcements/domain/Announcement.ts
  src/contexts/cda/announcements/infrastructure/PostgresAnnouncementRepository.ts
  src/contexts/cma/users/application/find/UserFinder.ts
  src/contexts/cma/users/application/search-by-criteria/UsersByCriteriaSearcher.ts
  src/contexts/cma/users/domain/UserDoesNotExist.ts
  src/contexts/cma/users/domain/UserFinder.ts
  src/contexts/cma/users/domain/UserRepository.ts
  src/contexts/cma/users/domain/event/UserDomainEvent.ts
  src/contexts/cma/users/domain/event/UserRegisteredDomainEvent.ts
  src/contexts/cma/users/infrastructure/PostgresUserRepository.ts
  src/contexts/shared/domain/AggregateRoot.ts
  src/contexts/shared/domain/criteria/Criteria.ts
  src/contexts/shared/domain/criteria/FilterOperator.ts
  src/contexts/shared/domain/event/DomainEvent.ts
  src/contexts/shared/domain/event/DomainEventClass.ts
  src/contexts/shared/domain/event/DomainEventSubscriber.ts
  src/contexts/shared/infrastructure/PostgresConnection.ts
  src/contexts/shared/infrastructure/criteria/CriteriaToPostgresSqlConverter.ts
  src/contexts/shared/infrastructure/criteria/CriteriaToSqlConverter.ts
  src/contexts/shared/infrastructure/event-bus/DomainEventJSONDeserializer.ts
  src/contexts/shared/infrastructure/event-bus/DomainEventJSONSerializer.ts
  src/contexts/shared/infrastructure/event-bus/rabbitmq/RabbitMQConnection.ts
  src/contexts/shared/infrastructure/event-bus/rabbitmq/RabbitMQEventBus.ts
  src/contexts/system/email/application/send-welcome-email/SendWelcomeEmailOnUserRegistered.ts
  src/contexts/system/email/domain/WelcomeEmail.ts
  src/contexts/system/email/domain/event/WelcomeEmailSentDomainEvent.ts
  src/contexts/system/email/infrastructure/MailjetEmailSender.ts
  src/contexts/system/email/infrastructure/SendgridEmailSender.ts
  src/scripts/configure-rabbitmq.ts
  src/scripts/consume-rabbitmq.ts
  tsconfig.json
Labels: enhancement
